import type { Metadata } from "next";
import "@fontsource/inter/index.css";
import "@fontsource/nunito/index.css";
import "@fontsource/ibm-plex-mono/index.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ background: 'linear-gradient(135deg, var(--pastel-blue), var(--pastel-pink))', minHeight: '100vh' }}>
      <body
        className="antialiased"
        style={{
          fontFamily: 'InterVariable, NunitoVariable, IBM Plex Mono Variable, Arial, sans-serif',
        }}
      >
        {children}
      </body>
    </html>
  );
}
